import mongoose from "mongoose";
import College from "../models/College";

const MONGODB_URI = "mongodb+srv://toriiijournal_db_user:Sneha%402620@collegediscovery.mg10cas.mongodb.net/college-discovery";
const colleges = [
    {
        name: "Indian Institute of Technology Bombay",
        location: "Mumbai",
        state: "Maharashtra",
        fees: 250000,
        rating: 4.8,
        courses: ["B.Tech", "M.Tech", "MBA", "PhD"],
        placementPercentage: 98,
        avgPackage: 2100000,
        description: "Premier engineering institute known for excellence in technology and research.",
        image: "https://upload.wikimedia.org/wikipedia/en/1/1d/IIT_Bombay_Logo.svg",
        established: 1958,
        type: "Government",
        cutoffRanks: { JEE: 100 },
    },
    {
        name: "Indian Institute of Technology Delhi",
        location: "New Delhi",
        state: "Delhi",
        fees: 240000,
        rating: 4.7,
        courses: ["B.Tech", "M.Tech", "MBA", "PhD"],
        placementPercentage: 97,
        avgPackage: 2000000,
        description: "Top engineering institute located in the capital city.",
        image: "",
        established: 1961,
        type: "Government",
        cutoffRanks: { JEE: 150 },
    },
    {
        name: "BITS Pilani",
        location: "Pilani",
        state: "Rajasthan",
        fees: 550000,
        rating: 4.6,
        courses: ["B.Tech", "M.Tech", "MBA", "B.Pharmacy"],
        placementPercentage: 95,
        avgPackage: 1800000,
        description: "Leading private engineering institute with strong industry connections.",
        image: "",
        established: 1964,
        type: "Private",
        cutoffRanks: { JEE: 500 },
    },
    {
        name: "National Institute of Technology Trichy",
        location: "Tiruchirappalli",
        state: "Tamil Nadu",
        fees: 180000,
        rating: 4.5,
        courses: ["B.Tech", "M.Tech", "MBA", "MCA"],
        placementPercentage: 93,
        avgPackage: 1500000,
        description: "One of the top NITs known for placements and academics.",
        image: "",
        established: 1964,
        type: "Government",
        cutoffRanks: { JEE: 2000 },
    },
    {
        name: "Vellore Institute of Technology",
        location: "Vellore",
        state: "Tamil Nadu",
        fees: 480000,
        rating: 4.3,
        courses: ["B.Tech", "M.Tech", "MBA", "MCA", "B.Sc"],
        placementPercentage: 88,
        avgPackage: 800000,
        description: "Large private university with diverse programs and global exposure.",
        image: "",
        established: 1984,
        type: "Deemed",
        cutoffRanks: { JEE: 8000 },
    },
    {
        name: "Delhi Technological University",
        location: "New Delhi",
        state: "Delhi",
        fees: 160000,
        rating: 4.2,
        courses: ["B.Tech", "M.Tech", "MBA"],
        placementPercentage: 87,
        avgPackage: 900000,
        description: "Premier state university focused on engineering and technology.",
        image: "",
        established: 1941,
        type: "Government",
        cutoffRanks: { JEE: 5000 },
    },
    {
        name: "Manipal Institute of Technology",
        location: "Manipal",
        state: "Karnataka",
        fees: 520000,
        rating: 4.2,
        courses: ["B.Tech", "M.Tech", "B.Pharmacy", "MBA"],
        placementPercentage: 85,
        avgPackage: 750000,
        description: "Well-known private institute with strong alumni network.",
        image: "",
        established: 1957,
        type: "Private",
        cutoffRanks: { JEE: 10000 },
    },
    {
        name: "SRM Institute of Science and Technology",
        location: "Chennai",
        state: "Tamil Nadu",
        fees: 450000,
        rating: 4.0,
        courses: ["B.Tech", "M.Tech", "MBA", "B.Sc", "BCA"],
        placementPercentage: 82,
        avgPackage: 650000,
        description: "Large private university with multiple campuses across India.",
        image: "",
        established: 1985,
        type: "Deemed",
        cutoffRanks: { JEE: 15000 },
    },
    {
        name: "Amity University",
        location: "Noida",
        state: "Uttar Pradesh",
        fees: 400000,
        rating: 3.9,
        courses: ["B.Tech", "MBA", "BBA", "B.Sc", "LLB"],
        placementPercentage: 78,
        avgPackage: 550000,
        description: "Private university offering diverse programs with industry tie-ups.",
        image: "",
        established: 2005,
        type: "Private",
        cutoffRanks: { JEE: 20000 },
    },
    {
        name: "Indian Institute of Management Ahmedabad",
        location: "Ahmedabad",
        state: "Gujarat",
        fees: 2300000,
        rating: 4.9,
        courses: ["MBA", "PhD", "Executive MBA"],
        placementPercentage: 100,
        avgPackage: 3200000,
        description: "India's top business school with world-class faculty and placements.",
        image: "",
        established: 1961,
        type: "Government",
        cutoffRanks: { CAT: 99 },
    },
    {
        name: "Indian Institute of Management Bangalore",
        location: "Bengaluru",
        state: "Karnataka",
        fees: 2200000,
        rating: 4.8,
        courses: ["MBA", "PhD", "Executive MBA"],
        placementPercentage: 100,
        avgPackage: 3000000,
        description: "Premier management institute in the Silicon Valley of India.",
        image: "",
        established: 1973,
        type: "Government",
        cutoffRanks: { CAT: 98 },
    },
    {
        name: "AIIMS New Delhi",
        location: "New Delhi",
        state: "Delhi",
        fees: 50000,
        rating: 4.9,
        courses: ["MBBS", "MD", "MS", "B.Sc Nursing", "PhD"],
        placementPercentage: 99,
        avgPackage: 1200000,
        description: "India's most prestigious medical institute.",
        image: "",
        established: 1956,
        type: "Government",
        cutoffRanks: { NEET: 50 },
    },
    {
        name: "Christian Medical College",
        location: "Vellore",
        state: "Tamil Nadu",
        fees: 120000,
        rating: 4.7,
        courses: ["MBBS", "MD", "MS", "B.Sc Nursing"],
        placementPercentage: 97,
        avgPackage: 1000000,
        description: "Renowned medical college with exceptional clinical training.",
        image: "",
        established: 1900,
        type: "Private",
        cutoffRanks: { NEET: 200 },
    },
    {
        name: "Jadavpur University",
        location: "Kolkata",
        state: "West Bengal",
        fees: 80000,
        rating: 4.4,
        courses: ["B.Tech", "M.Tech", "B.Sc", "M.Sc", "PhD"],
        placementPercentage: 88,
        avgPackage: 900000,
        description: "Reputed state university known for engineering and arts programs.",
        image: "",
        established: 1955,
        type: "Government",
        cutoffRanks: { JEE: 6000 },
    },
    {
        name: "PSG College of Technology",
        location: "Coimbatore",
        state: "Tamil Nadu",
        fees: 200000,
        rating: 4.3,
        courses: ["B.Tech", "M.Tech", "MBA", "MCA"],
        placementPercentage: 90,
        avgPackage: 750000,
        description: "Top autonomous engineering college in South India.",
        image: "",
        established: 1951,
        type: "Private",
        cutoffRanks: { JEE: 7000 },
    },
];

async function seed() {
    try {
        await mongoose.connect(MONGODB_URI);
        console.log("✅ Connected to MongoDB");

        await College.deleteMany({});
        console.log("🗑️ Cleared existing colleges");

        await College.insertMany(colleges);
        console.log(`🌱 Seeded ${colleges.length} colleges successfully!`);

        await mongoose.disconnect();
        console.log("👋 Disconnected from MongoDB");
        process.exit(0);
    } catch (error) {
        console.error("❌ Seed failed:", error);
        process.exit(1);
    }
}

seed();